### ISSUE TITLE
[1.12.2] [CsokiCraftUtil] Eating an item with a GorgeRecipe causes server crash

### ISSUE THREAD

**Issue by Landiie** [bence98/GorgeCore#2]
Eating any of the default shipped items with recipes causes the game to crash. tried creating my own with the auto generator, and manually via json, with no success. Here is the crash log. [1.12.2 gorge core crash](https://pastebin.com/vyBh6dzt)

**Comment by bence98** [comment]
Yes, I see the problem, and it has nothing to do with recipes; in fact, it is a bug in CsokiCraftUtil! It seems as if some Forge mappings changed underneath it, but that shouldn't have happened... Strange. I'll surely look into it.

**Comment by Landiie** [comment]
thank you so much! if this is fixed it will solve so many hacky fixes within out pack, <3

**Comment by Foreck1** [comment]
Hi, sorry to bother with this, as the bug has already been documented and tracked down, but I just wanted to say that I really hope it can get fixed so that I can use this mod too. It's pretty novel and I like it a lot! Would love to see it updated after 3 years. ^^

**Comment by bence98** [comment]
Did a quick fix, use this version (1.3.7) of CsokiCraftCore: https://www.curseforge.com/minecraft/mc-mods/csokicraftutil/files/3167364
(GorgeCore doesn't need to be updated)
If I'll have a lot of time, I'll completely redesign CsCrCo, because it has become a hot mess :/
If you experience problems with the update, be sure to reply back here. Otherwise I'll close this as Fixed after a week.
And a happy new year! :)

**Comment by bence98** [comment]
I take it has been resolved
